title: "War Games"
description: "A blog on baseball stats and Python-based analytics"
baseurl: "/war_games" # important if you're using a project site
url: "https://silvesco94.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
